### ISSUE TITLE
Find only works for current page

### ISSUE THREAD

**Issue by adopilot** [alanjuden/MvcReportViewer#11]
Apologies   for spanning whit so many issues.
I am so excited to keep alive SSRS on my .NET core project that I can't  restrain quite,

When report viewer page load report whit multiple pages.
If you try to find something that is not on current  page there is no results.
Find works only for current page, (it works prry OK)
But we usually load reports whit multiple pages and users expect that find works through all report.

**Comment by alanjuden** [comment]
@adopilot: I was able to duplicate this and have been having issues with my RS at work so I've not been able to fully test out my fix. I believe I need to restart SSRS.
