### ISSUE TITLE
Error unable to access page  https://alanjuden.com/

### ISSUE THREAD

**Issue by phinq17192016** [alanjuden/MvcReportViewer#115]
Hello Alan Juden i am trying to learn about AlanJuden.MvcReportViewer.NetCore but the link https://alanjuden.com/2016/11/10/mvc-net-core-report-viewer/ failed to view. Can you give specific instructions on how to use AlanJuden.MvcReportViewer.NetCore?

**Comment by alanjuden** [comment]
@phinq17192016, thanks for reaching out. I've got my site working again...sorry about that!

**Comment by phinq17192016** [comment]
Thanks @alanjuden I see the site is back up and running
