### ISSUE TITLE
Getting started is hard

### ISSUE THREAD

**Issue by martindlarsson** [alanjuden/MvcReportViewer#12]
Hello!
Your project seems interesting after testing other libraries that tries to do the same thing but with iframe and web forms which is not that nice.

I have spent a couple hours trying to get your library into my simple web application and failing. I am using Visual Studio 2013.

First I installed the Nuget package "ASP.NET MVC". It created som boilerplate code but no dll was referenced so I got two compiler errors of this type: The type or namespace name 'AlanJuden' could not be found (are you missing a using directive or an assembly reference?)
Then I found your dll inside the git-repo (under nuget\lib\net452). Copied that file into my project and referenced it. The I got the exact same two compile errors as before!

Then I open you .sln file from the git-repo but when building that I got lots of compiler errors of this type: Unexpected character '$' in HtmlHelperExtensions.cs and ReportServiceHelper.cs. Looking at your code in git in the browser I can see there are $ signs sprinkled here and there, should it be there? If so, how do I make it compile?
Also Nuget could not download Microsoft.Net.Compilers.props and ApplicationInsights. All other Nuget packages was downloaded and installed properly.

Can you help me out here? This might not be an issue but in my opinion you need to clarify the documentation a bit and package your solution so that it is easier to get started.

Thanks for the great work though! This stuff is really needed.

**Comment by alanjuden** [comment]
Hello @martindlarsson, if I had to make a bet...your existing project's .net version is set to a lesser version than mine is set for (mine is set to .net 4.5.2 as you noticed from nuget\lib\net452). Please check your project's .net version and see if you are possibly set to .net 3.5 or .net 4.0 instead of at least 4.5.2. Also, I'm assuming that your using standard .net rather than .net core.

**Comment by martindlarsson** [comment]
That might be the case that my project is set to 4.5 but when opening your
solution I am using your settings. Then it should compile if it compiles
for you, right?
I'm using standard .net, not core.

**Comment by alanjuden** [comment]
Correct - opening my solution and compiling should work as long you have .NET 4.5.2 framework installed on your computer.

The issue in your project is that visual studio seems to ignore any references that are above your project's .net framework version so it acts as if the reference doesn't exist (it usually highlights the reference with a yellow triangle if you expand your references section). 

However, it should be relatively painless to update your framework version from the project properties screen.

**Comment by alanjuden** [comment]
@martindlarsson: did my suggestion work for you?

**Comment by martindlarsson** [comment]
I left my computer at work. Have to try it on Monday. Thanks!

**Comment by martindlarsson** [comment]
Moving up to 4.5.2 did the trick. Though you are using C# 6 features which not is available in Visual Studio 2013. So that is why the project did not compile.
I am having some other issues as well but I'm going to try to fix them myself, otherwise open new issues here.

**Comment by alanjuden** [comment]
Thanks for reporting back @martindlarsson. I'm going to close this one out now.
