### ISSUE TITLE
Unicode in report name not supported

### ISSUE THREAD

**Issue by martindlarsson** [alanjuden/MvcReportViewer#13]
In MvcReportViewer/AlanJuden.MvcReportViewer.ExampleWebsite/Views/Report/ReportViewer.cshtml line 123 you need to use @HttpContext.Current.Server.UrlEncode(Model.ReportPath) to support Unicode in report names. I got in to trouble when my report with name 'G01-Åldersfördelning av revisionspatienter per organisation' was rendered.

I also changed:
protected virtual System.Text.Encoding Encoding { get { return System.Text.Encoding.ASCII; } }
to:
protected virtual System.Text.Encoding Encoding { get { return System.Text.Encoding.Unicode; } }
I don't know if it has any impact though but in general I think you should use Unicode if support for other languages other than English is desirable.

**Comment by alanjuden** [comment]
@martindlarsson: I've checked in a fix for this. However in my testing, changing the override for the Encoding property to Unicode from ASCII on the ReportController made bad things happen! I did modify the logic to pass in the appropriate encoding into the SSRS server and it spits out some crazy stuff! I have however changed the .cshtml file to include .UrlEncode() anywhere that I'm using the Model.ReportPath.
