### ISSUE TITLE
Report with not all parameters set to default values at load time

### ISSUE THREAD

**Issue by martindlarsson** [alanjuden/MvcReportViewer#14]
I get an `ArgumentNullException` on line 34 in ReportController.cs, contentData.ReportData is null, when loading a report where not all parameters are set to default. The user has to choose alternatives for a few parameters which also cascades to the next parameter. For example the user needs to choose organisation and then specify which department in a drop down.

There is an exception thrown inside ExportRerportToFormat in ReportServiceHelper.cs:
`"This report requires a default or user-defined value for the report parameter 'rpDepartment'. To run or subscribe to this report, you must provide a parameter value. ---> Microsoft.ReportingServices.Diagnostics.Utilities.ReportParameterValueNotSetException: Th...`
which then causes the ArgumentNullException above.

**Comment by alanjuden** [comment]
@martindlarsson: I'd be interested to hear how your report parameters are setup on this particular report. I'm already doing some checking prior to running the report from within the HtmlHelperExtensions & CoreHtmlHelpers on this line:

if (model.IsMissingAnyRequiredParameterValues(contentData.Parameters))

**Comment by martindlarsson** [comment]
I have 9 parameters that the user needs to fill in. I have used you example code where this code `@Html.RenderReportViewer(Model)` is at the bottom of the view. This seems to render the report no matter if the parameters are set. In HtmlHelperExtensions.cs on line 15 you run the `ExportToFormat `function and way down on line 127 you check if alla parameters are set. Seems like you should do this bofore exporting to format?
When `model.IsMissingAnyRequiredParameterValues(parameters)` is called, `this.Parameters` is empty... As I mentioned before I get an exception when this is called `service.Render2`. That might cause the parameters to be blank!?

**Comment by martindlarsson** [comment]
I have done some fiddling with the code you might be interested in. Im sorry to say that I didnt find a solution though.

In HtmlHelperExtensions I added this code `var parameters = ReportServiceHelpers.GetReportParameters(model, false);` and commented out `var contentData = ...` and som code that referenced it. Now I got all the parameters and the `reportParameter.DefaultValues` is null as expected. So I check if it is null in some places. This brings up the reportparameters in the view but it does not show all drop downs as it should, instead it shows them as textboxes.

**Comment by alanjuden** [comment]
Martin, could you pass along more info about your parameters for the report
you're testing with?

Out of curiosity, do they have default values setup and do they allow null
or blanks?

Thanks,

Alan

**Comment by martindlarsson** [comment]
My report has, among other, one parameter that is a list of choices that
does not allow null or blanks but allow multiple selected values. It is a
list of organizations. No default value is set.
An other parameter is a list of years, same setup as for organizations
except no multiple values.

Do you need more? Those are the params that causes the exception.

**Comment by alanjuden** [comment]
Martin, could you send me the contents or a copy of your
ReportViewer.cshtml file that's used on the front end as the report viewer
page please? I'm curious if maybe your file is out of date from the current.

Thanks,

Alan

**Comment by martindlarsson** [comment]
I use the contents of ReportViewer.cshtml and I copied it from the dec 28th revision . I have made some smaller adjustments to it for test purposes. Now I copied the feb 28th revision of the file and ran it and I got the same result. Since I have commented out the line `ReportServiceHelpers.ExportReportToFormat...` in HtmlHelperExtensions.cs and replaced with `var parameters = ReportServiceHelpers.GetReportParameters(model, false);` it runs without exceptions but the parameter dropdowns are not filled with selectable values.
I dont know it will help you but I attach my report file here.
[G07-Ålder vid första undersökningen.zip](https://github.com/alanjuden/MvcReportViewer/files/833573/G07-Alder.vid.forsta.undersokningen.zip)

**Comment by martindlarsson** [comment]
I installed VS 2017 and opened the MvcReportViewer solution. Changed the server url and the report path. Now I see some more fields filled in but I get a `NullException` on line 34 in `ReportController.cs. contentData.ReportData` is null.

**Comment by Deus-Adder-Ex** [comment]
I'm having the same issue. I am running v1.0.5. The call to Render2 in ReportExportResult throws an exception stated in the original post. The parameter referenced in the exception is contained within the executionInfo passed to the method.

This exception is silently handled, but results in the other exception Martin is stating.

Here is my report, hopefully it helps.
[BenTestUsers.zip](https://github.com/alanjuden/MvcReportViewer/files/834140/BenTestUsers.zip)

**Comment by alanjuden** [comment]
@martindlarsson & @Deus-Adder-Ex: just curious if you guys have kept up to date on this library and done any further testing? I've created a report that goes against a sample Northwind database and it has one pre-filled parameter and then a date field that is not pre-filled but is required. I'm able to run the report the initial time and I see a message on my control indicating "Please fill parameters and run report...". If I click the "View Report" button prior to having my date field filled in, I then receive a red error message in the control "Report failed to load, check report parameters...". Do you get these at all?

**Comment by martindlarsson** [comment]
Sounds good. I will try again tonight.

/Martin

ons 22 mars 2017 kl 06:06 skrev Alan Juden <notifications@github.com>:

**Comment by Deus-Adder-Ex** [comment]
I'm also looking into this. I am no longer getting missing parameter errors, but now am getting a different issue with parameters.  I can build sample reports that run correctly, but my production reports aren't filling in the parameters or using them in the queries. I'll post again if I can find what the discrepancy is. Thank you for all your time and effort in this!

**Comment by martindlarsson** [comment]
With the updated code I now get an ArgumentNullException in ReportController.cs on line 43 `var content = model.Encoding.GetString(contentData.ReportData);` where `contentData.ReportData` is null.

![2017-03-23 15_27_36-alanjuden mvcreportviewer debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/14070530/24252349/895956e6-0fdd-11e7-9bba-3b0c1f91023b.png)

I think the parameters that can be filled in is, but as @Deus-Adder-Ex mentions, some of my parameters cascade. For instance, the report I am testing right now you have to choose start-year and when you have done that the parameter end-year is filled in. Example, start-year is set to 2012, then end-year can only hold years beginning at 2013 and onward. The two parameters have separate Datasets using the same stored procedure (SP). The SP takes two parameters and creates a list of integers in that interval, from and too. The end-year (ni the report) uses the filled in parameter (start-year) as the first argument to the SP to generate its list of options. Makes sense?

![2017-03-23 15_40_10-report parameter properties](https://cloud.githubusercontent.com/assets/14070530/24253192/ebf7c4f2-0fdf-11e7-813d-ddcfd246baf2.png)

**Comment by alanjuden** [comment]
@martindlarsson: I'm not sure that the cascading will work on my control as of this point. I can try to recreate a report that uses cascading parameters and see what I can do but I'm not making any promises around it. 

If you hit F5 and continue running, the error will be caught by the ReportViewer.cshtml page.

Which has this logic:

$.get("/Report/ViewReportPage/?reportPath=@Model.ReportPath.UrlEncode()&page=" + page + "&" + urlParams)
				.done(function (data) {
					updateReportContent(data);
					hideLoadingProgress();

					if (afterReportLoadedCallback && typeof (afterReportLoadedCallback) == "function") {
						afterReportLoadedCallback();
					}
				})
				.fail(function (data) {
					$('.ReportViewerContent').html("<div class='ReportViewerError'>Report failed to load, check report parameters...</div>");
					hideLoadingProgress();
				});

Notice the ".fail()" method in the js. It's handling errors at the server side and showing a message of "Report failed to load, check report parameters...".

**Comment by alanjuden** [comment]
@martindlarsson: I have just created a new ticket around the cascading issue (https://github.com/alanjuden/MvcReportViewer/issues/24)

I'm intending on closing this ticket after you test out the error handling as mentioned in the last comment.

**Comment by martindlarsson** [comment]
OK, sounds good. I will be trying to find a way to make this work as well.
Thank you for your patience.

tors 23 mars 2017 kl 16:04 skrev Alan Juden <notifications@github.com>:
