### ISSUE TITLE
Sort buttons

### ISSUE THREAD

**Issue by mcgiany** [alanjuden/MvcReportViewer#15]
Hi,
are you considering on support of sort buttons?
In some of my reports, i have deffined user sort. But buttons are not displayed when using ReportViewer.

thanks

**Comment by alanjuden** [comment]
@mcgiany: any chance you could explain a little further of how your sort is being accomplished in the report? I've never really had to add any sorting to my reports other than in the queries.

**Comment by mcgiany** [comment]
@alanjuden: yes. It's called interactive sort. I've created one demo report for you.
With this script, you create a database (in your localhost SQL Server) that is required for this report:

```
CREATE DATABASE demo
GO

USE demo
GO

CREATE TABLE Projects (
Id INT IDENTITY(1,1) NOT NULL,
ProjectName VARCHAR(50) NOT NULL,
Budget DECIMAL(18,4) NOT NULL,
CONSTRAINT pkProjects PRIMARY KEY (Id))
GO

INSERT INTO Projects
VALUES ('Dummy project', 100), ('Test project', 200), ('GitHub project', 300)
GO
```
In report builder i just set interactive sort for tablix:
![interactive_sort](https://cloud.githubusercontent.com/assets/14090031/23250104/f98e503e-f9a7-11e6-89f8-d92eeac53907.png)

Then it looks like this. You can click on the arrow in report, and the rows are sorting.
![demo](https://cloud.githubusercontent.com/assets/14090031/23250132/14ba5f2e-f9a8-11e6-89be-deb55dc407dd.png)

Here is the report that works with the demo database. Just unzip, open in report builder and click run:
[demo.zip](https://github.com/alanjuden/MvcReportViewer/files/795860/demo.zip)

**Comment by alanjuden** [comment]
Thanks for the info @mcgiany...I'll see what I can do.

**Comment by alanjuden** [comment]
@mcgiany, I've been doing some research tonight on this and it's not looking hopeful. 

The [api reference](https://msdn.microsoft.com/en-us/library/ms155395.aspx) indicates that the "ResourceStreamRoot(*)" feature I need has been deprecated in the SSRS api since 2012 as mentioned here: https://msdn.microsoft.com/en-us/library/ms143509(v=sql.120).aspx
