### ISSUE TITLE
Connecting to SSRS Servers through HTTPS is not functioning properly

### ISSUE THREAD

**Issue by alanjuden** [alanjuden/MvcReportViewer#16]
This was reported to me via email on my website from the contact page. Figured I should add a ticket for it.

**Comment by alanjuden** [comment]
I've checked in a fix that I think will work for this but could really use someone with a SSL'd server to test it out for me! :D

**Comment by dineshmike** [comment]
I tried this today with my ReportServer and able to view the pages through HTTPS.

**Comment by alanjuden** [comment]
@dineshmike, thanks for taking the time to test this out for me!
