### ISSUE TITLE
Does not support .net framwork 4.6.1

### ISSUE THREAD

**Issue by basharsvu** [alanjuden/MvcReportViewer#17]
I tried to install on my .net core project but a dependency error appeared showing that it dose not support .net framework 4.6.1 .

**Comment by alanjuden** [comment]
@basharsvu: I have two available projects out here...one is for standard .NET (4.5.2 and higher) and the other is for .NetCore. It sounds like you may have the standard .NET dll included in your .NetCore project which wouldn't work.

**Comment by basharsvu** [comment]
Dear, 
Am using the project for .net core, sorry i couldn't understand what do you mean by standard .net in .net core. ?1 .
its pure .net core project running on .net 4.6.1 , i have installed your library for .net core and in my project reference showing a clear message (....  dose not support .net framework 4.6.1).
So did you tested on .net 4.6 and is it working fine ? .

Thank you for your response

**Comment by alanjuden** [comment]
@basharsvu: I have created a dll that's entirely for .NetCore and another dll that's for .Net Framework version 4.5.2 and higher. You are mixing .NetCore and .Net framework 4.6.1 together similar to this issue: https://github.com/alanjuden/MvcReportViewer/issues/5

Try reading that other closed issue and see if his suggestion works for you.

**Comment by basharsvu** [comment]
Yes now i see your point, Thank you for the clarification , but acutely i need .net framework on my project so, if there is  way in the future to fit it under .net framework also it will be great.
Nice job thanks alot.
