### ISSUE TITLE
Report Server User Permission 

### ISSUE THREAD

**Issue by basharsvu** [alanjuden/MvcReportViewer#21]
Dear,
what's the required permission need to grant to my Application pool user to access the report server service throw your tool.
When i configure the report server service account to use built in account (Local System), every thing works fine. But actually in production environment am not allowed to do that, the service will run in specif domain account which i don't have access to it.
I tried to grant access full permission from the report manager, but this will not work if the service account not local system.
Do you have any suggestion or clarification on permission grants.

Thanks in advanced.

**Comment by alanjuden** [comment]
@basharsvu,

For my testing environment, I have setup my SSRS service to run as my local user account. I have also given my local user account permissions from the SSRS web management on the root directory. I didn't really have to change the Application pool user on IIS. Then in my controller, I used the default security context: return System.Net.CredentialCache.DefaultNetworkCredentials;

For my production instance, my network guys have created a single Active Directory user for me to use. Let's call the user "reportservicesuser". 

1. First thing you have to do is give your domain user access on your report server. 
2. Navigate to your report server and hit the "Folder Settings" button. 
3. Click "New Role Assignment".
4. In the "Group or user name" text field, you'll want to use your domain account "MYDOMAIN\reportserviceuser" and apply the correct checkboxes for the access that your user needs.
5. Configure your ReportController to return the appropriate user permissions: return new System.Net.NetworkCredential("reportserviceuser", "password", "MYDOMAIN");

Hope this helps.

Alan

**Comment by basharsvu** [comment]
Thanks Dear,
