### ISSUE TITLE
UseCustomReportImagePath

### ISSUE THREAD

**Issue by basharsvu** [alanjuden/MvcReportViewer#28]
Dear,

Could you please gave an example on how to use CustomReportImagePath in my report?

Thanks a lot.

**Comment by alanjuden** [comment]
@basharsvu, I created the ReportImagePath as a way for someone to override the path in case you're needing to use a different controller name other than "Report". The reason this property was created, along with the UseCustomReportImagePath was to allow for somewhat of a proxy for viewing the images from the report server. My report server instance is internally housed but I'm making the reports visible on a public site that some users may not have access to the internal report server.

To use these properties, you'll just need to add override properties for them in your report controller of your website.

`		protected override string ReportImagePath
		{
			get
			{
				return "/MyDifferentControllerName/ReportImage/?originalPath={0}";
			}
		}

		protected override bool UseCustomReportImagePath
		{
			get
			{
				return true;
			}
		}`

One thing to note, is that you don't have to override ReportImagePath unless your report controller isn't called "ReportController". It's instead called something else. If you just want to use the custom report image path to view the files, then you only need the bool override.

Hope this helps.

Alan

**Comment by basharsvu** [comment]
Thank you dear, this is very helpful specially in case that i don't to view the report URL in my application,
So this is will override any image in the report with the custom path  ? so is there a way to put multi different images ?! 

thanks

**Comment by alanjuden** [comment]
@basharsvu, by using the "UseCustomReportImagePath" set to true, it will change all images in your report to use the local site path automatically.
