### ISSUE TITLE
Dropdown values are not escaped

### ISSUE THREAD

**Issue by mcgiany** [alanjuden/MvcReportViewer#31]
Hi,

i found that values in dropdown parameters are not escaped for HTML. I have parameter, where the first option has value "&lt;Select period &gt;". And the report is rendered like this:
![escape](https://cloud.githubusercontent.com/assets/14090031/26351288/54e15f30-3fb7-11e7-92b7-541a8ab39ce5.png)

**Comment by alanjuden** [comment]
Just patched this, I'll get out a new build shortly.
