### ISSUE TITLE
Reports w/Images Prompt UserName/Password

### ISSUE THREAD

**Issue by cgountanis** [alanjuden/MvcReportViewer#45]
Works with simple reports no images but if you run a report with a watermark or logo you get a user/pass browser prompt from SSRS. Any way we can embed the session or something from the existing network creds into that too?

Reports w/Images Prompt UserName/Password

**Comment by alanjuden** [comment]
@cgountanis,

Try one thing for me before we get crazy here :P

On your report controller, can you override the UseCustomReportImagePath and return true? This will create a link to download the image. I had to use this on my so that it would make like a proxy to download the images in the original context of the SSRS request since my server is internally available and not externally available.

Let me know what happens.

Alan

**Comment by cgountanis** [comment]
Yeah exactly we have the same thing SSRS is internal (not public facing IP or anything) and the WWW does all the communications. I can not in good faith ever run an open SSRS server public facing, will try your suggestion and report back. Overall I think we are falling back on just using Export to PDF as the default option as that works perfectly and is mobile friendly.

Side question: Is there any information about MS releasing a NUGET package for MVC/Core anywhere for future planning?

**Comment by cgountanis** [comment]
Works for the logo in the header but not the watermark.

**Comment by cgountanis** [comment]
I think the issue is it ignores images within the background tag.

background-image:url(http... etc...

**Comment by cgountanis** [comment]
Got it working had to add a second replace for background images within public static string ReplaceImageUrls(). It is pretty raw and I am sure it could be combined or cleaned up but this is the basic gist.

```
var searchForUrl2 = $"background-image:url({reportServerDomainUri.Scheme}://{reportServerDomainUri.DnsSafeHost}/";
//replace image urls with image data instead due to having issues accessing the images as a different authenticated user
var imagePathIndex2 = reportContent.IndexOf(searchForUrl2);
while (imagePathIndex2 > -1)
{
	var endIndex = reportContent.IndexOf("\"", imagePathIndex2 + 21);   //account for the length of background-image:url("
	if (endIndex > -1)
	{
		var imageUrl = reportContent.Substring(imagePathIndex2 + 21, endIndex - (imagePathIndex2 + 21));
		reportContent = reportContent.Replace(imageUrl, $"{String.Format(model.ReportImagePath, imageUrl)}");
	}

	imagePathIndex2 = reportContent.IndexOf(searchForUrl2, imagePathIndex2 + 5);
}
```
