### ISSUE TITLE
Blog post on alanjuden.com not available

### ISSUE THREAD

**Issue by ExcaliburVT** [alanjuden/MvcReportViewer#52]
@alanjuden your blog post with the detailed instructions appears to be down:

https://alanjuden.com/2016/11/10/mvc-net-core-report-viewer/

Thanks you for all your work on this!

**Comment by alanjuden** [comment]
Thanks for reporting this @ExcaliburVT. Looks like it should be all good now.

**Comment by ExcaliburVT** [comment]
Awesome thank you!
