### ISSUE TITLE
Problem whit encoding on non English chars

### ISSUE THREAD

**Issue by adopilot** [alanjuden/MvcReportViewer#56]
Is there a way to setup correct encoding for report viewer so non English chars render as shoud.
My views usually using UTF-8-Boom encoding whit Central European Windows  -1250 character sets.
I did setup .net Core app and report viewer works pretty good.
Only problem is when I have non English chars on my report as (žćčđšŽĆČĐŠ) I do get wrong encoding.

![sumnicinareportserveru](https://user-images.githubusercontent.com/4448913/34354601-cf2ec5d4-ea2f-11e7-87cd-f8f957b2cf8b.JPG)

**Comment by alanjuden** [comment]
Hello @adopilot,

Someone else recently asked about this below was my response (it was on my blog in the comments).

> On the ReportController you can override it at a global level (for all your reports) by overriding the “Encoding” property…or you can set it individually on each report model if you have a lot of differences in Encoding by using the “Encoding” property on the model in your ReportController action methods.
