### ISSUE TITLE
How can i set parameters when the only thing i want to use is ExportReport?

### ISSUE THREAD

**Issue by hbernardic** [alanjuden/MvcReportViewer#58]
I'd like to get my report as .pdf and set one parameter before doing that but I dont see how i should do that without altering your code, specifically the ExportReport method. Any suggestions?

**Comment by alanjuden** [comment]
Hey @hbernardic , it sounds like you're really just trying to have an export happen via a link...is that a correct assumption?

I would just make a link that looks like this:

https://mysite.com/Report/ExportReport/?reportPath=urlEncodedPathToReport&format=pdf&parameter1=foo&parameter2=bar

I hope this helps!

Alan

**Comment by hbernardic** [comment]
I have an SPA app that targets my API in which I have modified your ExportReport method by adding "parameters" attribute. Wouldn't want to target my reporting service directly from SPA app. Don't know if that's the correct decision but i got it working. If you have other suggestions plz tell me. Thanks

**Comment by alanjuden** [comment]
I'm glad you got it working!
