### ISSUE TITLE
It's possible to render RDLC ?

### ISSUE THREAD

**Issue by velkumars** [alanjuden/MvcReportViewer#64]
@alanjuden, Good day, 

I have a RDLC report, its possible to render my RDLC and generate PDF?

**Comment by alanjuden** [comment]
@velkumars, it is not possible to use a .rdlc file. This project requires a report server to work because it's using the report server api's to render the data of the reports.

Another question already asking about it.
https://github.com/alanjuden/MvcReportViewer/issues/7
