### ISSUE TITLE
Could not load file or assembly 'System.ServiceModel.Http

### ISSUE THREAD

**Issue by AquaNerd** [alanjuden/MvcReportViewer#65]
I built an app using example but got this error.  Could not load file or assembly 'System.ServiceModel.Http

I am on .netcore 2.1.

**Comment by aroraarjita** [comment]
Hi @AquaNerd,

You need to use the compatible version of System.ServiceModel.Http.
It should be added as a reference in the solution.

**Comment by AquaNerd** [comment]
You can close this issue
