### ISSUE TITLE
Can this library be used to convert a RDLC file into a PDF?

### ISSUE THREAD

**Issue by tomRedox** [alanjuden/MvcReportViewer#83]
We're in the middle of porting a full .NET Framework app to .NET Core and at the moment we use the ReportViewer to render reports from rdlc report definition files.  

We don't need a visual report viewer on the and we aren't hooking up to SSRS, we're just creating a `LocalReport` and then calling 'Render' that to get the bytes for the PDF.

Is it possible to do something similar with this library?

**Comment by alanjuden** [comment]
@tomRedox, you could essentially just call into your "/Report/ExportReport/?reportPath=pathtoyourreport&format=PDF&yourparameter=parametervalue" method passing the info that would be necessary. Or you could bypass my code altogether and then call the reporting services api directly to do what you need.

**Comment by tomRedox** [comment]
@alanjuden thanks very much for the speedy response.

The full .net version of our code was using Microsoft.ReportingServices.ReportViewerControl.WebForms, but that's not working in Core.  I was hooking up the datasets manually like this

```
var localReport = new LocalReport
{
    ReportPath = HttpContext.Current.Server.MapPath("~/bin/Reports/SoaReport.rdlc")
};

// 98414
var soa = await _soaBuilder.GetBuiltSoaAsync(saleId);

ReportDataSource reportDataSource = new ReportDataSource
{
    Name = "DataSet1",
    // datasource has to be a table or a list, so put our single
    // object in a list
    Value = new List<SoaHeader> { soa }
};

ReportDataSource reportDataSource2 = new ReportDataSource
{
    Name = "DataSet2",
    Value = soa.SoaTransList
};

// Datasets are already defined in the designer, we're just hooking them up to our data here.
localReport.DataSources.Add(reportDataSource);
localReport.DataSources.Add(reportDataSource2);
``` 
And then I was getting the rendered report using 

```
// Landscape PDF
string deviceInfo = "<DeviceInfo>" +
                    "  <OutputFormat>" + reportType + "</OutputFormat>" +
                    "  <PageWidth>11.7in</PageWidth>" +
                    "  <PageHeight>8.3in</PageHeight>" +
                    "  <MarginTop>0.5in</MarginTop>" +
                    "  <MarginLeft>0.5in</MarginLeft>" +
                    "  <MarginRight>0.5in</MarginRight>" +
                    "  <MarginBottom>0.5in</MarginBottom>" +
                    "</DeviceInfo>";

localReport.EnableExternalImages = true;

string mimeType;
string encoding;
Warning[] warnings;
string[] streams;

byte[] renderedBytes = localReport.Render(
    reportType,
    deviceInfo,
    out mimeType,
    out encoding,
    out fileNameExtension,
    out streams,
    out warnings);
```

I've just added your library to our solution and I was looking at the `AlanJuden.MvcReportViewer.ReportViewerModel` but couldn't see a way to actually pass in the data to be used by the report?

I might be completely misunderstanding the purpose of this library though, I'm not sure if it's actually intended/suitable for loading data into an RDLC file and rendering it without having a SSRS server running somewhere in the background?

**Comment by tomRedox** [comment]
Ah, looking through the old closed issues I see this library[ doesn't support LocalReport](https://github.com/alanjuden/MvcReportViewer/issues/69#issuecomment-422789151), so I'm guessing I'm trying to do something unsupported here.

**Comment by alanjuden** [comment]
@tomRedox, correct - this library does not work with local report files. It requires server reports that are living in a report server.
