### ISSUE TITLE
is this for SSRS or local report?

### ISSUE THREAD

**Issue by oishiimendesu** [alanjuden/MvcReportViewer#88]
It's supposed to connect to reporting services server.

Why did you use?:
	model.ReportPath = "/Folder/Report File Name";

**Comment by alanjuden** [comment]
This is only for SSRS, it **does not support local reports**.

I have written a blog post about setting this up here: https://alanjuden.com/2016/11/10/mvc-net-core-report-viewer/

The model.ReportPath you're referring to is the path from the report server's perspective. There is another setting on your ReportController that allows you to configure the path to the report server: ReportServerUrl (which is mentioned in the blog post I referenced above).

I hope this helps.

Alan

**Comment by oishiimendesu** [comment]
thanks,
