### ISSUE TITLE
Strange behavior on Returning on Report Viewer Page before closing print tab 

### ISSUE THREAD

**Issue by adopilot** [alanjuden/MvcReportViewer#9]
Scenario is like this.
User open report viewer page.
It is works prefect, paging, view report etc.
User click on print,
Chrome open-up new tab ready for printing.
If user return on Report Viewer tab before closing Print tab.
Report viewer does not works.
When you click view report again it is Loading forever (until close print tab).
Paging also load forever.

Can we left some message on main report view page for user to close print tab.
Or can we remain report-viewer page ruining even there is print tab opened.

**Comment by alanjuden** [comment]
That is an interesting behavior that I hadn't noticed. I usually use Chrome for my browser and I was able to duplicate what you're saying. I also tested it in Internet Explorer 11 and I believe it *somewhat* behaves like IE. 

IE launched a new tab and the print dialog window but I was unable to switch tabs. I believe Chrome is trying to let you still interact with the other page but is somehow having an issue with showing the print dialog in a modal window. Not sure that I have much control over this behavior.

**Comment by adopilot** [comment]
Regarding the issue whit HTML printgn
https://github.com/alanjuden/MvcReportViewer/issues/10
Maybe is best approach to print do opening PDFs inside new tab.
That will close bout issues.
I do not like rendering and returning PDFs directly from SSRS because it has MMIE type file
If we just can render PDFs on server-side and  add  header('Content-type: application/pdf'); to returning requests It will be great.
User will get PDF ready for print.
Same way it does ReportViewer2016 offical contol for WinForms
