### ISSUE TITLE
Boostrap 4 Support

### ISSUE THREAD

**Issue by sgopimca7** [alanjuden/MvcReportViewer#96]
Thanks for this great tool.

As of now we are using bootstrap 4.3.1. 

The Report Viewer screen great when we use the bootstrap 3 version, But the design breaks when we use the bootstrap 4.3.1.

**Boostrap 3:**

![Boostrap 3](https://user-images.githubusercontent.com/31735142/76309686-460c2f00-62f3-11ea-8be9-a943cef18b9a.PNG)

**Boostrap 4:**

![Boostrap 4](https://user-images.githubusercontent.com/31735142/76309689-473d5c00-62f3-11ea-9c0a-0703a38d46dc.PNG)

Please help on this issue.

Thanks and Regards,

Gopi.S

**Comment by tiesont** [comment]
The markup [this class](https://github.com/alanjuden/MvcReportViewer/blob/master/AlanJuden.MvcReportViewer/HtmlHelperExtensions.cs) generates was not really valid before, but Bootstrap 3's styles would let it more or less work as intended. With the updates that Bootstrap 4 introduced to the grid system, the layout is breaking how it probably should have before. 

What's my point, then? Well, someone just needs to update that class to generate the correct grid markup, and then it should work on both versions of Bootstrap. I'd imagine it wouldn't be too difficult of a pull-request.
